# Increases the amount of memory Gradle can use and optimizes the GC
# -XX:+UseZGC
org.gradle.jvmargs=-Xmx4G
# Helps with build times
org.gradle.parallel=true
# Caches Dependencies for faster build times.
org.gradle.caching=true

# Fabric Properties
    # Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
    minecraftVersion=26.2
    loaderVersion=0.19.3

# Mod Properties
    modId = ethans_kotlin_extensions
    modVersion = 2.1
    modLoader = Fabric
    mavenGroup = net.frozenblock
    baseName = EthansKotlinExtensions

# Dependencies
    fabricKotlinVersion=1.13.13+kotlin.2.4.10
